### PR TITLE
Allow to change sku for prod and fix app function kind

### PR DESCRIPTION
**Pull request by ElfoLiNk**
To change the function app plan we need to taint the function before applying:

`terraform taint module.operator_search.azurerm_function_app.this`

then we need to redeploy the function from https://dev.azure.com/pagopaspa/cgn-onboarding-portal-projects/_build?definitionId=34

### CODE REVIEW

**Review by uolter — APPROVED** [review]

**Comment by uolter** [comment]
@ElfoLiNk we can not put in the same rg plan based on Linux and Elastic .... which is based on windows I guess
Indeed I get the following error while applying. I assume we need one more resource group.

```
Error: Error creating/updating App Service Plan "cgnonboardingportal-u-os-plan" (Resource Group "cgnonboardingportal-u-api-rg"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Requested feature is not available in resource group cgnonboardingportal-u-api-rg. Please try using a different resource group or create a new one." Details=[{"Message":"Requested feature is not available in resource group cgnonboardingportal-u-api-rg. Please try using a different resource group or create a new one."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"59324","Message":"Requested feature is not available in resource group cgnonboardingportal-u-api-rg. Please try using a different resource group or create a new one.","MessageTemplate":"Requested feature is not available in resource group {0}. Please try using a different resource group or create a new one.","Parameters":["cgnonboardingportal-u-api-rg"]}}]
│ 
│   with module.operator_search.azurerm_app_service_plan.this,
│   on modules/app_function/main.tf line 2, in resource "azurerm_app_service_plan" "this":
│    2: resource "azurerm_app_service_plan" "this" {
```

**Comment by ElfoLiNk** [comment]
Ah, no i forgot to tell you to delete the plan manually, i was able to apply it in dev using the same resource group.

I got the same when `module.spid_login.azurerm_app_service.app_service: Modifying... ` but when created from scratch it worked

**Comment by uolter** [comment]
> Ah, no i forgot to tell you to delete the plan manually, i was able to apply it in dev using the same resource group.
> 
> I got the same when `module.spid_login.azurerm_app_service.app_service: Modifying... ` but when created from scratch it worked

sh*t it does not work to me .... even if I ran the taint command before the apply and the service plan is no more there ... when I try to recreate it it fails with the above error...... But it works when I create the function on the portal.
I'm gonna try a workaround ....

**Comment by uolter** [comment]
Unfortunately I had to create a new resource group. 
It is expected to work the possibility to have different service plan (linux and windows ) in the same resource group starting from Jan 2021 .... but it does not work to me.
It's just a terraform .... issue .... it works from the portal.

https://github.com/terraform-providers/terraform-provider-azurerm/issues/10020
https://docs.microsoft.com/en-us/azure/app-service/overview#app-service-on-linux

**Pull request merged**
