### PR TITLE
Add env vars for spid login and validate-jwt policy

### PR DESCRIPTION
**Pull request by ElfoLiNk**
- Environment variables for spid login
- validate-jwt policy
- fix vars

### CODE REVIEW

**Comment by ElfoLiNk** [comment]
@pasqualedevita @uolter 

```
    # TODO fix this
    METADATA_PUBLIC_CERT  = "./certs/cert.pem"
    METADATA_PRIVATE_CERT = "./certs/key.pem"
```

We need also to generate this cert and pass it to the application via file. How can we do it?

**Comment by uolter** [comment]
> @pasqualedevita @uolter
> 
> ```
>     # TODO fix this
>     METADATA_PUBLIC_CERT  = "./certs/cert.pem"
>     METADATA_PRIVATE_CERT = "./certs/key.pem"
> ```
> 
> We need also to generate this cert and pass it to the application via file. How can we do it?
@ElfoLiNk 
I am not sure I get what you need. By the way we also have an app service which uses a client certificate. We stored the certificate in the key vault and we read it as a string: 
https://github.com/pagopa/io-infrastructure-live-new/blob/master/prod/westeurope/external/apigad/app_service/terragrunt.hcl#L62
Can you use the same approach?

**Comment by ElfoLiNk** [comment]
> > @pasqualedevita @uolter
> > ```
> >     # TODO fix this
> >     METADATA_PUBLIC_CERT  = "./certs/cert.pem"
> >     METADATA_PRIVATE_CERT = "./certs/key.pem"
> > ```
> > 
> > 
> > We need also to generate this cert and pass it to the application via file. How can we do it?
> > @ElfoLiNk
> > I am not sure I get what you need. By the way we also have an app service which uses a client certificate. We stored the certificate in the key vault and we read it as a string:
> > [#18 (comment)](https://github.com/pagopa/cgn-onboarding-portal-infra/pull/18#issuecomment-831907958)
> > Can you use the same approach?

In that case do we need to ask @AleDore to change the application for reading it as string instead of loading as a file?

**Comment by uolter** [comment]
> > > @pasqualedevita @uolter
> > > ```
> > >     # TODO fix this
> > >     METADATA_PUBLIC_CERT  = "./certs/cert.pem"
> > >     METADATA_PRIVATE_CERT = "./certs/key.pem"
> > > ```
> > > 
> > > 
> > > We need also to generate this cert and pass it to the application via file. How can we do it?
> > > @ElfoLiNk
> > > I am not sure I get what you need. By the way we also have an app service which uses a client certificate. We stored the certificate in the key vault and we read it as a string:
> > > [#18 (comment)](https://github.com/pagopa/cgn-onboarding-portal-infra/pull/18#issuecomment-831907958)
> > > Can you use the same approach?
> 
> In that case do we need to ask @AleDore to change the application for reading it as string instead of loading as a file?

Yep, I had a quick chat with @AleDore .... he is going to change it ... otherwise I don't know how to do that in an easy way.
I applied this PR.... I'll wait to merge it.

**Comment by AleDore** [comment]
Now it is possible to set certificates directly as env variables :) @uolter @ElfoLiNk @pasqualedevita

**Review by uolter — APPROVED** [review]

**Pull request merged**
